FROM python:3.14-slim
LABEL org.opencontainers.image.source=https://github.com/dandi/s3-log-extraction
LABEL org.opencontainers.image.description="A Docker image of the main developer branch for the s3-log-extraction project."

# git required for hatch-vcs versioning
RUN apt-get update \
    && apt-get install -y git \
    && rm -rf /var/lib/apt/lists/*

ADD ./ s3-log-extraction
RUN cd s3-log-extraction && pip install --no-cache-dir ".[all]"
CMD ["s3logextraction"]
